config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  get '/search' => 'articles#search', :as => 'search_page'
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search  
    if params[:search].blank?  
        redirect_to(root_path, alert: "Empty field!") and return  
      else  
        @parameter = params[:search].downcase  
        @article = Article.all.where("lower(Title) LIKE :search", search: "%#{@parameter}%")  
      end  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:Title, :blog, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="align-middle ">
      <%= form.label :Title, class:"bg-warning text-bolder p-2" %>
      <%= form.text_field :Title, class:"form-control" %>
    </div>

    <div class="mt-3">
      <%= form.label :blog, class:"bg-warning text-bolder p-2" %>
      <%= form.text_area :blog, size: "30x20", class:"form-control" %>
    </div>

    <div class="mt-3 ">
      <%= form.label :author, class:"bg-warning text-bolder p-2" %>
      <%= form.text_field :author, class:"form-control" %>
    </div>

    <div class="mt-3">
      <%= form.submit class:"btn btn-danger" %>
    </div>
<% end %>

app/views/articles/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-primary bg-dark">
<%= link_to 'Articles', root_path, class:"navbar-brand text-light" %>
  <%# <a class="navbar-brand text-light" href="#">Articles</a> %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      <%= link_to 'New Article', new_article_path, class:"nav-link text-light" %>
      </li>
    </ul>
    
    <%= form_tag(search_page_path, :method => "get", class: 'navbar-form navbar-right') do %>  
      <div class="input-group">  
        <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
        <div class="input-group-btn">  
          <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => 'Search'%>  
        </div>  
      </div>  
    <% end %>
    <%# <form class="form-inline my-2 my-lg-0">

      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0 bg-danger text-light" type="submit">Search</button>
    </form> %>
  </div>
</nav>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<div class="text-center"><%= link_to 'Show', @article, class:"btn btn-info mr-1" %> 
<%= link_to 'Back', articles_path, class:"btn btn-info" %></div>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
<% @articles.each do |article| %>
<div class="col-sm-4">
  <div class="card mb-3" >
    <div class="card-body">
      <h5 class="card-title text-dark" style="font-weight: bolder;" >
        <%= article.Title %>
      </h5>
      <div class="card-text text-dark" style="background-color: rgb(180, 157, 175);">
        <%= article.blog.truncate(120) %>
        <%= article.author %>
      </div>
      <%= link_to 'Read More', article_path(article), class: "btn btn-info" %>
      <%# <%= link_to 'Show', article, class:'btn btn-info text-center' %>
      <%= link_to 'Edit', edit_article_path(article), class:'btn btn-info text-center mx-1'%>
      <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-info text-center' %>
    </div>
  </div>
</div>
<% end %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center m-2 text-dark bg-warning">New Article</h1>
<br>
<div class="container-fluid w-75"><%= render 'form', article: @article %></div>
<br>

<div class="text-center"><%= link_to 'Back', articles_path, class:'btn btn-danger text-center' %></div>

app/views/articles/search.html.erb
<h3>Search Result</h3>  
<%if @article.nil?%>
  <%= root_path %>
<%else%>
  <% @article.each do |article| %>  
        <%= article.Title %><br>
        <%= article.blog.truncate(110) %><br> 
        <%= link_to 'Read More', article_path(article), class: "btn btn-info" %> 
    <% end %>
<%end%>
    

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid">
  <div class="text-left text-dark bg-warning ml-3 p-1 font-weight-bolder" style="font-size: 20px; font-weight: bolder; opacity: 0.8;">
    <h4>Title:</h4>
    <%= @article.Title%>
  </div>

  <div class="text-left font-weight-bolder ml-3 text-dark bg-warning " style="opacity: 0.8;">
    <h2>Blog:</h2>
    <br>
    <div class="text-left mr-2 bg-light text-dark p-2" style= "font-size: 20px; font-weight: bold; color:rgb(9, 9, 27); ">
    <%= @article.blog %>
    </div>
  </div>

  <div class="text-left ml-3 text-dark bg-warning p-1" style="font-size: 20px; font-weight: bolder; opacity: 0.8;">
    <h3>Author:</h3>
    <%= @article.author %>
  </div>
</div>
<br>

<div class="text-center"><%= link_to 'Edit', edit_article_path(@article), class:"btn btn-danger mr-1" %>

<%= link_to 'Back', articles_path, class:"btn btn-danger" %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

  </head>

  <body>
  <%= render 'articles/header'%>
    <div class="conatiner">
      <%= yield %>
    </div>
  </body>
</html>